# Generated by Django 4.2.7 on 2023-12-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_discount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ProductApp.product'),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='special_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductApp.special_sale'),
        ),
    ]
